// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeqC0Jg7VkznrEvcQ35KL8QnXg7YDbeVU',
    appId: '1:381482007479:web:68bca9df58b9d51ccbc632',
    messagingSenderId: '381482007479',
    projectId: 'mutu-54548',
    authDomain: 'mutu-54548.firebaseapp.com',
    storageBucket: 'mutu-54548.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjI0mN1Y1Xr2ksRBWZQqKshOBBmsgEN4',
    appId: '1:381482007479:android:6052d634cfd31887cbc632',
    messagingSenderId: '381482007479',
    projectId: 'mutu-54548',
    storageBucket: 'mutu-54548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjBEWwZ3lgHaB16c-V7zF3Yba4Br2mStU',
    appId: '1:381482007479:ios:44ba4a068ed99843cbc632',
    messagingSenderId: '381482007479',
    projectId: 'mutu-54548',
    storageBucket: 'mutu-54548.appspot.com',
    iosClientId: '381482007479-u2aicq5kqi0sngkcui710ipqssq6pl0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjBEWwZ3lgHaB16c-V7zF3Yba4Br2mStU',
    appId: '1:381482007479:ios:44ba4a068ed99843cbc632',
    messagingSenderId: '381482007479',
    projectId: 'mutu-54548',
    storageBucket: 'mutu-54548.appspot.com',
    iosClientId: '381482007479-u2aicq5kqi0sngkcui710ipqssq6pl0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutu',
  );
}
